name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Java 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Uprawnienia gradlew
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Wrzuć jar
        uses: actions/upload-artifact@v4
        with:
          name: EasyKostium
          path: build/libs/*.jar
